@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Apr 09 00:47:15 +0800 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testbench_func_synth -key {Post-Synthesis:sim_1:Functional:testbench} -tclbatch testbench.tcl -view C:/Users/zhanggenqi/Desktop/DSP_in_VLSI/HW3/VIVADO/DSP_in_VLSI_HW3_v2/waveform/testbench_behav.wcfg -log simulate.log"
call xsim  testbench_func_synth -key {Post-Synthesis:sim_1:Functional:testbench} -tclbatch testbench.tcl -view C:/Users/zhanggenqi/Desktop/DSP_in_VLSI/HW3/VIVADO/DSP_in_VLSI_HW3_v2/waveform/testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
